// until we convert server-side code to TypeScript...

export const DATA_FOR = {
  NO_FILTERS: "noFilters",
  YEAR: "year",
  MONTH: "month",
  MONTH_YEAR: "monthYear",
  FIX: "fix",
  FIX_YEAR: "fixYear",
  FIX_MONTH: "fixMonth",
  FIX_MONTH_YEAR: "fixMonthYear",
  CODE: "code",
  CODE_YEAR: "codeYear",
  CODE_MONTH: "codeMonth",
  CODE_MONTH_YEAR: "codeMonthYear",
  CODE_FIX: "codeFix",
  CODE_FIX_YEAR: "codeFixYear",
  CODE_FIX_MONTH: "codeFixMonth",
  CODE_FIX_MONTH_YEAR: "codeFixMonthYear",
  ACCT: "acct",
  ACCT_YEAR: "acctYear",
  ACCT_MONTH: "acctMonth",
  ACCT_MONTH_YEAR: "acctMonthYear",
  ACCT_FIX: "acctFix",
  ACCT_FIX_YEAR: "acctFixYear",
  ACCT_FIX_MONTH: "acctFixMonth",
  ACCT_FIX_MONTH_YEAR: "acctFixMonthYear",
  ACCT_CODE: "acctCode",
  ACCT_CODE_YEAR: "acctCodeYear",
  ACCT_CODE_MONTH: "acctCodeMonth",
  ACCT_CODE_MONTH_YEAR: "acctCodeMonthYear",
  ACCT_CODE_FIX: "acctCodeFix",
  ACCT_CODE_FIX_YEAR: "acctCodeFixYear",
  ACCT_CODE_FIX_MONTH: "acctCodeFixMonth",
  ALL_FILTERS: "allFilters"
};
